### ISSUE TITLE
agent: add cooldown period

### ISSUE THREAD

**Issue by lgfa29** [hashicorp/nomad-autoscaler#12]
One of the strategies to avoid resource count instability is to add a cooldown period in which changes in metric values do not affect scaling decisions.

The cooldown is defined as a time period (e.g., '5s') and its value is derived out of the following locations:

* default global value (least precedence)
* default Autoscaler agent configuration
* policy specific (highest precedence)

**Comment by eveld** [comment]
Would this also work for just registered jobs? e.g. a startup grace period in case startup consumes a lot of resources and then drops down (looking at you Java apps).
