### ISSUE TITLE
docs: add internal section detailing node_class usage in horizontal cluster scaling

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad-autoscaler#255]
The use of `node_class` within a cluster scaling policy is not well documented despite its importance. The Nomad Autoscaler documentation should be enhanced with a new internal section which covers this, in particular these key areas:

- node_class requirement
- what happens if a node(s) is not configured with a node_class config parameter
- how nodes are search and filtered when performing scaling in actions

related #254

**Comment by lgfa29** [comment]
Doc updates in https://github.com/hashicorp/nomad/pull/14950
