### ISSUE TITLE
demo: hey install binaries are no longer available breaking usage of demos

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad-autoscaler#270]
[rakyll/hey](github.com/rakyll/hey) is used within the autoscaler demos to generate load and connections to scalable example HTTP services. Currently the [download links are broken](https://github.com/rakyll/hey/issues/222) which means the demos do not work as documented.

There are a couple of ways we could potentially solve this:
- remove use of `hey` and identify replacement, although what is to say we don't experience this with a new tool
- compile the binary from source during demo build
- compile the binary from source and host this somewhere we control

**Comment by attachmentgenie** [comment]
hey is packaged by upstream for focal [1] so perhaps upgrading the demo to ubuntu 20.04 is worth looking into 

[1] https://packages.ubuntu.com/focal/hey
