### ISSUE TITLE
demo: add Datadog cluster scaling query example

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad-autoscaler#281]
@nicgrayson reached out on hangops with the following:
> There isn't a datadog example of that query but i think that is a datadog problem not a nomad problem. Is there a place i should PR to add a dd example?

It would be useful to find the correct place to include examples like this to help users get started quicker. Initial thoughts are either the target plugin documentation, or including them within the demo so users can optionally switch.

**Comment by nicgrayson** [comment]
@jrasell got datadog working. I could just comment out an example and put it here: https://github.com/hashicorp/nomad-autoscaler/blob/master/demo/remote/aws_autoscaler.nomad#L70

I could also make a new directory with no promethus in it.

**Comment by jrasell** [comment]
Hi @nicgrayson. I agree with adding the example as a comment in the current jobspec and then maybe a small callout in the README explaining the possibility of using Datadog. It would probably be also worth adding an example of running the DD plugin [here](https://github.com/hashicorp/nomad-autoscaler/blob/master/demo/remote/aws_autoscaler.nomad#L37).
