### ISSUE TITLE
Docker image doesn't have an entrypoint

### ISSUE THREAD

**Issue by lgfa29** [hashicorp/nomad-autoscaler#304]
The Nomad Autoscaler Docker image doesn't have an entrypoint defined, which forces users to set a command if they pass a flag.

```shellsession
$ docker run hashicorp/nomad-autoscaler:0.2.0-beta2 -help
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"-help\": executable file not found in $PATH": unknown.
ERRO[0000] error waiting for container: context canceled
```

**Comment by josegonzalez** [comment]
How is the docker image generated?

**Comment by lgfa29** [comment]
The image is built from another repo that we use to standardize the release process across multiple tools/projects. It's an "easy" fix, I just need to make sure I won't break anything else 😅
