### ISSUE TITLE
Support multiple policies in a single file

### ISSUE THREAD

**Issue by josegonzalez** [hashicorp/nomad-autoscaler#307]
Currently, each policy must be in a new file, making it more or less impossible to elastically update the policies if deploying the nomad-autoscaler in nomad. You can't inject a custom consul-template stanza at runtime, so you'd need a sidecar process that would write the templates out for you, and then some other mechanism to send a sighup to the nomad-autoscaler task if any of those files change...

**Comment by lgfa29** [comment]
That's a good point @josegonzalez. Requiring the Autoscaler job to be re-deployed or having to have some sidecar monitoring the file system are not great.

But I am not sure if having multiple policies in the same file would fix this, you would still need to change and monitor that single file.

We will think about a better approach to fix this problem. Thanks for raising it 👍

**Comment by josegonzalez** [comment]
A single file is a bit easier to handle at the moment than multiple files via a single run of consul-template. You could imagine a struct that contains a dynamic list of policies that change as autoscaling groups get added, removed, or changed for a given class type.

Writing a single consul-template file is much easier than writing multiple in that case, especially if you consider calling it via consul-template nomad's built-in integration; it's basically impossible to add a new policy that way without redeploying a new job spec.

**Comment by lgfa29** [comment]
Yup, I agree it's easier to manage a single file. 

But what I meant in my previous message is that this feels more like a symptom of a bigger issue, where storing policies in files doesn't scale very well. It's fine for one or two policies that don't change much, but as the number grows or the policies get more dynamic it becomes very hard to manage.

My current thinking is that having some sort of API would be the ideal solution for this case. Then you can `PUT`/`DELETE` policies and Autoscaler just `GET` and monitor them for changes.

How do you feel about this approach?

**Comment by josegonzalez** [comment]
This seems good from an external API workflow, but my concern here is that you'd essentially need both a way to bootstrap policies on `nomad-autoscaler` start - maybe a sidecar task that pulls down initial policies so nomad-autoscaler can read it? - and something that will push updates as necessary (which I guess is a customer-level concern).
