### ISSUE TITLE
policy-evaluation: base worker SIGSEGV with empty query results

### ISSUE THREAD

**Issue by baxor** [hashicorp/nomad-autoscaler#321]
I was missing a close paren in my datadog query, but the entire autoscaler was unable to handle this condition and exited. 

```2020-12-02T19:29:18.225Z [WARN]  internal_plugin.datadog: empty time series response from datadog, try a wider query window
2020-12-02T19:29:18.225Z [WARN]  policy_eval.worker.check_handler: no metrics available: check=applications-scale-cpu-evaluation id=f66f0a4f-c0b6-58ca-f01e-ef74eeb2f036 policy_id=0620961e-676a-619b-6d74-4d3e06fa9c2e queue=cluster source=datadog strategy=target-value target=aws-asg
2020-12-02T19:29:18.232Z [WARN]  internal_plugin.datadog: empty time series response from datadog, try a wider query window
2020-12-02T19:29:18.232Z [WARN]  policy_eval.worker.check_handler: no metrics available: check=applications-scale-memory-evaluation id=f66f0a4f-c0b6-58ca-f01e-ef74eeb2f036 policy_id=0620961e-676a-619b-6d74-4d3e06fa9c2e queue=cluster source=datadog strategy=target-value target=aws-asg
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x19 pc=0x117c363]

goroutine 70 [running]:
github.com/hashicorp/nomad-autoscaler/policyeval.(*BaseWorker).handlePolicy(0xc000145310, 0x19fe460, 0xc00038a640, 0xc000d49680, 0x0, 0x0)
	/home/circleci/project/project/policyeval/base_worker.go:165 +0xac3
github.com/hashicorp/nomad-autoscaler/policyeval.(*BaseWorker).Run(0xc000145310, 0x19fe460, 0xc00038a640)
	/home/circleci/project/project/policyeval/base_worker.go:77 +0x2ed
created by github.com/hashicorp/nomad-autoscaler/agent.(*Agent).initWorkers
	/home/circleci/project/project/agent/agent.go:108 +0x1d6
2020/12/02 19:29:18.237457 [DEBUG] (cli) receiving signal "child exited"
2020/12/02 19:29:18.237471 [INFO] (runner) child process died
2020/12/02 19:29:18.237501 [ERR] (cli) child process died with exit code 2```

**Comment by josegonzalez** [comment]
Would be super great if instead of a segfault, we got a user-friendly error. Not sure if exiting non-zero is desired or not, but I'd say yes since its certainly a misconfiguration.

**Comment by baxor** [comment]
Ideally the autoscaler handles any issues and never exits since there will be other policies to service. IMO this should just be tracked as a failure in `nomad-autoscaler.policy.source.error_count` and perhaps a warning log message that there was not enough data to evaluate the policy or check if that is the case. if there are multiple checks and only one is lacking data, probably continue to evaluate, perform `scaleOut` if appropriate, but avoid any `scaleIn` actions.

**Comment by cgbaker** [comment]
Correct; panics are bugs. Which version of the autoscaler were you using?

**Comment by lgfa29** [comment]
Hi @baxor, 

I believe this is the same issue as #318, which was fixed #320.

Would you be able to try the [nigthly build](https://github.com/hashicorp/nomad-autoscaler/releases/tag/nightly) and see if you still have this problem?

**Comment by baxor** [comment]
Yes, I will give it a try.  I am using `0.2.0-beta3`.

Thanks

**Comment by baxor** [comment]
Nightly build seems to be working, thanks for the quick reply!

Now just to figure out why this query has no data via the APM despite returning data via DD notebooks/dashboards 🤔

**Comment by lgfa29** [comment]
I'm glad it's working for you now! 

And sorry for that breaking change in the query syntax. This project it's still early in development so we don't have any strong backwards compatibility guarantees. But this will change soon as the Autoscaler matures.

Feel free to open any new issue, even if it's not bug related. We would love to hear any feedback and feature requests.
