### ISSUE TITLE
deps: vulnerability within github.com/dgrijalva/jwt-go module

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad-autoscaler#339]
Vulnerable module: `github.com/dgrijalva/jwt-go`
Fixed in: `4.0.0-preview1`

## Detailed paths
- Introduced through: `github.com/hashicorp/nomad-autoscaler@0.0.0` › `github.com/Azure/go-autorest/autorest@0.11.0` › `github.com/Azure/go-autorest/autorest/adal@0.9.0` › `github.com/dgrijalva/jwt-go@3.2.0`
- Introduced through: `github.com/hashicorp/nomad-autoscaler@0.0.0` › `github.com/Azure/go-autorest/autorest/azure/auth@0.5.0` › `github.com/Azure/go-autorest/autorest/azure/cli@0.4.0` › `github.com/Azure/go-autorest/autorest/adal@0.9.0` › `github.com/dgrijalva/jwt-go@3.2.0`
- Introduced through: `github.com/hashicorp/nomad-autoscaler@0.0.0` › `github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-06-01/compute@44.0.0` › `github.com/Azure/go-autorest/autorest/azure@0.11.0` › `github.com/Azure/go-autorest/autorest@0.11.0` › `github.com/Azure/go-autorest/autorest/adal@0.9.0` › `github.com/dgrijalva/jwt-go@3.2.0`

## Overview
`github.com/dgrijalva/jwt-go` is a go implementation of JSON Web Tokens. Affected versions of this package are vulnerable to Access Restriction Bypass if `m["aud"]` happens to be `[]string{}`, as allowed by the spec, the type assertion fails and the value of aud is `""`. This can cause audience verification to succeed even if the audiences being passed are incorrect if required is set to false.

The affected library has unfortunately not seen any updates in 1 year.

**Comment by cgbaker** [comment]
Nothing on the autoscaler side (i.e., client side) performs JWT validation, correct? So there's no avenue for this to affect us?

**Comment by lgfa29** [comment]
Closed by #585
