### ISSUE TITLE
Runtime Panic: nomad apm plugin isn't implementing the APM interface

### ISSUE THREAD

**Issue by urjitbhatia** [hashicorp/nomad-autoscaler#340]
This is a bit of an embarrassing one. Seems like the nomad apm doesn't fully implement the APM interface 😐 

```
panic: interface conversion: *apm.RPC is not apm.APM: missing method QueryMultiple

goroutine 261 [running]:
github.com/hashicorp/nomad-autoscaler/policyeval.(*checkHandler).start(0xc00041df00, 0x1a10fa0, 0xc00041de80)
	/nomad-autoscaler-0.2.0/policyeval/base_worker.go:287 +0x412
created by github.com/hashicorp/nomad-autoscaler/policyeval.(*BaseWorker).handlePolicy
	/nomad-autoscaler-0.2.0/policyeval/base_worker.go:117 +0x38d
panic: interface conversion: *apm.RPC is not apm.APM: missing method QueryMultiple

goroutine 260 [running]:
github.com/hashicorp/nomad-autoscaler/policyeval.(*checkHandler).start(0xc00041dec0, 0x1a10fa0, 0xc00041de80)
	/nomad-autoscaler-0.2.0/policyeval/base_worker.go:287 +0x412
created by github.com/hashicorp/nomad-autoscaler/policyeval.(*BaseWorker).handlePolicy
	/nomad-autoscaler-0.2.0/policyeval/base_worker.go:117 +0x38d
```

**Comment by lgfa29** [comment]
Ouch...sorry for this....

The Nomad APM [does implement](https://github.com/hashicorp/nomad-autoscaler/blob/master/plugins/builtin/apm/nomad/plugin/metrics.go#L51) the `QueryMultiple` method, but the problem was that the RPC server and client did not.

#341 fixes this and we will get a release with the fix very soon.

**Comment by lgfa29** [comment]
Hi @urjitbhatia,

We release [v0.2.1](https://releases.hashicorp.com/nomad-autoscaler/0.2.1/) which contains the fix for this problem. 

Would you be able to test the new version and see if the problem is fixed?

Feel free to re-open this issue the panic still persists on v0.2.1.

**Comment by urjitbhatia** [comment]
Thanks @lgfa29 
Ran the new version but then immediately hit https://github.com/hashicorp/nomad-autoscaler/issues/303
The autoscaler ran for a little bit and then just got blocked.
Another thing we are seeing is that the evaluations aren't running at the right intervals - we expect say 2m if we set it in the policy but it is taking 5-10m sometimes between evals of the same policy

**Comment by lgfa29** [comment]
Yeah....#303 is my current priority. In the mean time, perhaps you can try to increase the number of workers that the agent starts. 

In the Autoscaler config file, you can set this in the [`policy_eval.workers`](https://www.nomadproject.io/docs/autoscaling/agent#workers) map. Workers are goroutines, which are relatively lightweight, so you could increase it by quite a bit. This is just band-aid, of course, but it would make more workers available when some of them get blocked.

As for the policies not being evaluated at the right interval, this is an interesting problem that I haven't thought before. We have a broker that distributes and dedups policy evaluation requests across workers. 

The `evaluation_interval` controls how often policies are sent to the broker, but given that workers are getting stuck, it doesn't guarantee that the policy will be evaluated immediately.

I will open an issue for this so we can keep track of it. Thanks for reporting it!
