### ISSUE TITLE
Dynamic Application Sizing not found within Nomad Enterprise license

### ISSUE THREAD

**Issue by henrikjohansen** [hashicorp/nomad-autoscaler#350]
I really wanted to play with the new DAS feature but it fails due to a license check : 

`[ERROR] agent: failed to run enterprise initialization: error="feature "Dynamic Application Sizing" not found within Nomad Enterprise license"`

However, we do run Nomad Enterprise : 

```
$ nomad license get
Product        = nomad
License Status = valid
License ID     = xxxxx
Customer ID    = xxxx
Expires At     = xxxx
Terminates At  = xxxx
Datacenter     = *
Modules:
        governance-policy
Licensed Features:
        Automated Upgrades
        Enhanced Read Scalability
        Redundancy Zones
        Namespaces
        Resource Quotas
        Audit Logging
        Sentinel Policies
        Automated Backups
        Multi-Vault Namespaces
```

I suspect this error is due to the fact that "Dynamic Application Sizing" is not mentioned as a specific feature - because our license was issued before DAS was a thing ... but DAS is listed as an included feature (see https://www.hashicorp.com/products/nomad/pricing)?

**Comment by jrasell** [comment]
Hi @henrikjohansen and apologies for this problem. What version of Nomad Enterprise are you currently running? Hopefully with this I can discuss internally the best way to solve this for you. In the mean time, there is a [Vagrant based DAS demo](https://github.com/hashicorp/nomad-autoscaler/tree/master/demo/vagrant/dynamic-app-sizing) if you have not run through this previously that could help scratch the itch.

**Comment by henrikjohansen** [comment]
No worries @jrasell :) 

Nomad servers are running v1.0.1 and our agents run a mix of v0.12.x and v1.0.1.

**Comment by jrasell** [comment]
Hi @henrikjohansen sorry for the delay in replying. It seems the license you are currently using only includes the `governance-policy` module, whereas the Dynamic Application Sizing feature comes bundled within the `Multi-Cluster and Efficiency` module. This is the cause for the Autoscaler check failure when attempting to run DAS.

I would recommend reaching out to your account manager here at HashiCorp who will be able to assist you further with this. I'll keep this issue open in case you have any follow up questions for me.

**Comment by henrikjohansen** [comment]
Thanks @jrasell - I'll have a chat with our HC account manager :+1:
