### ISSUE TITLE
Reload Credentials on SIGHUP

### ISSUE THREAD

**Issue by jeffwecan** [hashicorp/nomad-autoscaler#375]
We're currently running the autoscaler as a Nomad job with an AWS ASG configured as a target. The autoscaling job is using STS credentials for AWS authentication and a Nomad ACL token that are both retrieved from Vault. Naturally, Nomad restarts the autoscaler alloc as these credentials approach their TTLs and are renewed. When this occurs in the middle of a scale in event, we end up with drained and ineligible, but not terminated, nodes left in the ASG seemingly indefinitely. The series of events goes something like:

1. autoscaler starts draining a node
2. Before the node drain is complete, Nomad restarts the autoscaler alloc to template in new Vault credentials
3. The new autoscaler allocation seemingly has no state tracking the started-but-not-completed node scale in activity

If the behavior of autoscaler + a SIGHUP signal was extended to cover reloading any potential credential sources that would resolve our immediate issue. Alternatively, if there is an existing mechanism to support this usage, please do let us know! 😄

**Comment by cgbaker** [comment]
hey @jeffwecan , excellent timing. we just ran into this issue with a customer as well, and we're looking at ways of properly handling that state in the autoscaler as well as via Nomad APIs.

the workaround for the customer is to modify the policy evaluation interval, but that won't work for your case where the autoscaler is restart. if we come up with something else, we'll let you know. in the meantime, we'll prioritize SIGHUP support.

**Comment by cgbaker** [comment]
related: #376
