### ISSUE TITLE
Support reloading config on SIGHUP

### ISSUE THREAD

**Issue by cgbaker** [hashicorp/nomad-autoscaler#40]
Later, certain bits of config may be provided by vault (e.g., Nomad ACL token, APM auth credentials). Therefore, we may need the ability to reload config. It may be preferable to do this via a reload in the long term, on receipt of SIGHUP.

This may involve significant API changes, if we're doing to pass new config to, e.g., Target, Scaling, and APM plugins.

**Comment by lgfa29** [comment]
Closed by #390
