### ISSUE TITLE
accept additional apm (wavefront) plugin?

### ISSUE THREAD

**Issue by fredwangwang** [hashicorp/nomad-autoscaler#406]
Hi!

I am testing the nomad-autoscaler with Wavefront, and wrote the plugin: https://github.com/hashicorp/nomad-autoscaler/compare/master...fredwangwang:wavefront-apm

I followed the same code style mostly as prometheus plugin.
Also did manually tested using the following configuration:
```
strategy "target-value" {
  driver = "target-value"
}

apm "wavefront" {
  driver = "wavefront"

  config = {
    address    = "xxx.wavefront.com"
    wf_api_key = "00000000-0000-0000-0000-000000000012"
  }
}

nomad {
  address = "http://127.0.0.1:4646"
  region  = "global"
  token   = "00000000-0000-0000-0000-000000000034"
}
```

and the following scaling stanza in the job file.
```
scaling {
  enabled = true
  min     = 1
  max     = 10

  policy = {
    evaluation_interval = "5s"
    cooldown            = "20s"

    check "active_instance" {
      source = "wavefront"
      query  = "max(ts(nomad.client.allocs.cpu.user, job='test-job'))"

      strategy "target-value" {
        target = 20
      }
    }
  }
}
``` 

it is able to fetch metric and scale as expected.

If the additional apm plugin is welcomed, I'd be happy to create a pr right away. 😃

**Comment by jrasell** [comment]
Hi @fredwangwang, great work, this looks very useful. This is something we will discuss internally across the team, then come back with an answer.

**Comment by idrennanvmware** [comment]
@jrasell  - we would love to contribute and add this functionality.   Given we use Wavefront almost exclusively, adding this plug in helps us not have to create a prometheus cluster for something we already have access to :)

**Comment by jrasell** [comment]
Thank you again for taking the time to create this plugin.  

After investigating and discussing the plugin, the team ultimately believes it would be better as an external plugin and therefore reside within its own repository owned by yourself. We do not have any experience using Wavefront nor an easy way to test it, meaning we would not be able to provide the support we believe is necessary for code within this repository.

We will work on adding a documentation space for community plugins on the Nomad website. This plugin can then have an entry here allowing Nomad users to easily find details of both official and community plugins.  

Please let us know if you have any questions or comments.   It is worth making clear, the Nomad Autoscaler utilises the same plugin system as Nomad drivers, and so external plugins can be used seamlessly.

Thanks,
jrasell and the Nomad Ecosystem team

**Comment by fredwangwang** [comment]
Thanks for the reply! Will keep it a separate repo instead
