### ISSUE TITLE
Scaling down > 20 instances at once in AWS ASG fails

### ISSUE THREAD

**Issue by nathankleyn** [hashicorp/nomad-autoscaler#412]
Hello! 👋 

We are using the `nomad-autoscaler` to effectively scale up for running large batch jobs and then back down again at the end. However we are seeing the autoscaler throw errors when trying to scale down more than 20 instances at a time (anything less works a-ok!)

**Steps To Reproduce:**

1. Create an AWS ASG with a maximum capacity of > 20.
2. Create a policy like this:

```hcl
scaling "my_amazing_scaling" {
  enabled = true
  min     = 0
  max     = 21

  policy {
    cooldown            = "2m"
    evaluation_interval = "30s"

    check "desired" {
      source = "prometheus"
      query  = "21" # <- change this to 0 and see what happens
      strategy "target-value" {
        target = 0
      }
    }

    target "aws-asg" {
      dry-run             = "false"
      aws_asg_name        = "your_asg"
      node_class          = "your_asg"
      node_drain_deadline = "5m"
    }
  }
}
```
3. Wait for boxes to scale up.
4. Change `query` from `"21"` to `"0"`.

**Expected Behaviour:**

The autoscaler should correctly terminate all 21 instances.

**Actual Behaviour:**

The autoscaler fails to terminate the instances with the following error:

```
2021-03-03T18:09:08.148Z [ERROR] policy_eval.worker: failed to evaluate policy: eval_id=<id> eval_token=<id> id=<id> policy_id=<id> queue=cluster err="failed to scale target: failed to perform scaling action: failed to scale in AWS AutoScaling Group: failed to detach intances from Autoscaling Group: ValidationError: List exceeds the maximum number of instances to detach. Please retry your request with fewer instances.
	status code: 400, request id: <id>"
```

This is because there is a maximum limit of 20 instances in a single detch call in the AWS API:

> You can use AttachInstances, DetachInstances, EnterStandby, and ExitStandby with at most 20 instance IDs at a time.

https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-account-limits.html

**Comment by cgbaker** [comment]
thanks for the report, @nathankleyn , we'll add some logic around this.

**Comment by nathankleyn** [comment]
Thanks so much for super quick triage @cgbaker! 🙌 
Let me know if there's anything I can do to help the team reproduce of provide further info, very glad to assist. 🙂
