### ISSUE TITLE
DigitalOcean Cluster auto scaling 

### ISSUE THREAD

**Issue by patademahesh** [hashicorp/nomad-autoscaler#414]
Are there any plans to support other cloud providers such as DigitalOcean ?

**Comment by jrasell** [comment]
Hi @patademahesh and thanks for opening this request. There are no immediate plans to add this support, however, this could change depending on the community desire for such an addition. I would therefore ask anyone else looking at this issue who would also like this addition to please add a +1 to the opening comment.

In the meantime we would certainly be happy to guide and assist anyone in the community who wanted to write this plugin themselves. The use of [go-plugin](https://github.com/hashicorp/go-plugin) means APM, Strategy, and Target plugins can be developed independently and without the need to modify the core codebase.

**Comment by jsiebens** [comment]
FYI: https://github.com/jsiebens/nomad-droplets-autoscaler

**Comment by jrasell** [comment]
Hi @jsiebens, amazing work, thank you!

The Nomad website includes [this page](https://www.nomadproject.io/docs/autoscaling/plugins/external) detailing externally available plugins for the Nomad Autoscaler. It is basic, but a start. Would you be willing to raise a PR adding your DO plugin to this page?

**Comment by jsiebens** [comment]
Hi @jrasell,
PR for the addition on the website is created: https://github.com/hashicorp/nomad/pull/10408

**Comment by jrasell** [comment]
Thanks again @jsiebens, that PR has been approved and merged.

I will keep this issue open until the Nomad website is released with the updated documentation. Please feel free to reach out to us if you have any questions or comments regarding the plugin interface and implementation. We are always happy to help or receive feedback.

I am personally very interested in trying this plugin out :D

**Comment by patademahesh** [comment]
Is there any example/doc on how to use this plugin with nomad autoscaler ?

**Comment by jrasell** [comment]
Hi @patademahesh; I have opened https://github.com/hashicorp/nomad/pull/10448 to add a clearer paragraph detailing how to use external plugins with the Nomad Autoscaler. I hope this helps.

Thanks again @jsiebens, this is amazing! I will now close this issue; if there are questions about the plugin please raise them on the plugin repo, otherwise please feel free to raise additional issues against this repo for general questions or problems.
