### ISSUE TITLE
Scaling up from 0 not possible

### ISSUE THREAD

**Issue by dpogorzelski** [hashicorp/nomad-autoscaler#424]
Hello,
please consider the following scenario: 
after the autoscaler scaled a GCP MIG to 0 nodes it won't be able to scale up again when a job is submitted because of:
```
2021-03-17T10:44:16.749Z [WARN]  policy_eval.worker: failed to run check: id=c912b170-5aa7-a36d-83fd-079f1fdb35b5 policy_id=323c8cc5-e238-f91a-7a22-96abdd2824f3 queue=cluster target=gce-mig err="failed to query source: no nodes identified within pool"
```
the policy looks like this:
```hcl
scaling "cluster_policy" {
  enabled = true
  min     = 0
  max     = 3

  policy {

    cooldown            = "1m"
    evaluation_interval = "1s"

    check "cpu_allocated_percentage" {
      query = "percentage-allocated_cpu"

      strategy "target-value" {
        target = 70
      }
    }

    check "mem_allocated_percentage" {
      query = "percentage-allocated_memory"

      strategy "target-value" {
        target = 70
      }
    }

    target "gce-mig" {
      project             = "foobar"
      region              = "europe-north1"
      mig_name            = "mymig"
      node_class          = "default"
      node_drain_deadline = "5m"
    }
  }
}
```
Any ideas on how to solve this? If scaling down to 0 is permitted then it makes sense it should also be possible to scale up from 0 :)

**Comment by jrasell** [comment]
Hi @dpogorzelski and thanks for opening this. This is certainly a problem within the Nomad APM and how it should handle this situation.

**Comment by jrasell** [comment]
Hi again @dpogorzelski. This issue has been discussed internally and we have identified https://github.com/hashicorp/nomad/issues/9046 as something which is precursor any updates within this repository. The issue is currently being looked into and we will be sure to keep these issues updates so progress can be tracked.

**Comment by lgfa29** [comment]
Hi @dpogorzelski 👋 

After investigating this further I realized that there's really not good way to support scaling to zero clients with the Nomad APM....

#534 goes into more details and provide a fix to prevent the cluster from being stuck to zero. Feel free to add any comments or feedback on the approach I took there 🙂

**Comment by dpogorzelski** [comment]
Hey @lgfa29 , thanks for the followup, I think this makes sense :)

**Comment by lgfa29** [comment]
Nice! Feel free to reach out again if you have any other question 🙂
