### ISSUE TITLE
Node selector strategies don't take node class in consideration

### ISSUE THREAD

**Issue by lgfa29** [hashicorp/nomad-autoscaler#461]
When node selector strategies look for nodes to remove, they don't look at the node class defined in the policy This causes the selector to potentially return nodes that don't exist in the cluster being targeted.

Ref.: https://discuss.hashicorp.com/t/aws-nomad-autoscaler-multi-region-aws-asg-in-one-nomad-container/23073

**Comment by jrasell** [comment]
Initial thought here is that the [`ClusterScaleInNodeSelector`](https://github.com/hashicorp/nomad-autoscaler/blob/d48a6ec48e056894a33721e9896376ef5cb69e43/sdk/helper/scaleutils/nodeselector/selector.go#L13) doesn't and shouldn't be doing filtering of the API stub list response. This role is fulfilled by the [`ClusterNodePoolIdentifier`](https://github.com/hashicorp/nomad-autoscaler/blob/d48a6ec48e056894a33721e9896376ef5cb69e43/sdk/helper/scaleutils/nodepool/nodepool.go#L7) interface which is called within [`IdentifyScaleInNodes`](https://github.com/hashicorp/nomad-autoscaler/blob/d48a6ec48e056894a33721e9896376ef5cb69e43/sdk/helper/scaleutils/cluster.go#L111) before passing the filtered list to [`ClusterScaleInNodeSelector.Select`](https://github.com/hashicorp/nomad-autoscaler/blob/d48a6ec48e056894a33721e9896376ef5cb69e43/sdk/helper/scaleutils/cluster.go#L142).

I ran a quick test using a comparable setup (although not identical) to see if I could reproduce the behaviour using two ASG's and two scaling policies with the autoscaler built from `main`. I manually scaled each ASG alternating between them, to ensure the node list returned by Nomad has a mixed order between each node class. Everything worked as expected and there were no errors. I'll try and update my dev infra to completely mimic that described at some point today and re-run the test.

One curiosity from the reference post that I have been unable to figure so far is that the policies use the `node_class` pool identifier, however, the Prometheus queries are using a `region` label. This label isn't present in the standard Prometheus label set associated with the telemetry data points.

**Comment by petrukngantuk** [comment]
afaik, we run to this problems when ( as we use [terraform-aws-nomad](https://github.com/hashicorp/terraform-aws-nomad/blob/master/modules/nomad-cluster/main.tf) terraform module), the var.asg_name x var.cluster_name was different, it will cause like above behavior, if it's same is fine, not sure why it's like that

**Comment by jrasell** [comment]
Hi @petrukngantuk, I have taken a look through the linked module and have not identified any problems so far. The modules also do not seem to set `node_class` configuration option; are you able to provide information on how you configure the Nomad clients?

**Comment by petrukngantuk** [comment]
@jrasell , here is it

```hcl
bind_addr  = "0.0.0.0"
datacenter = "dc1"

client {
  enabled        = true
  node_class     = "us-east-1-aws-180"
  meta {
     ......
  }
}

consul {
  address = "127.0.0.1:8500"
}

telemetry {
  collection_interval        = "1s"
  disable_hostname           = true
  prometheus_metrics         = true
  publish_allocation_metrics = true
  publish_node_metrics       = true
}

plugin "docker" {
  .....
}

```

**Comment by jrasell** [comment]
@petrukngantuk thanks. I am curious if #474 was impacting you in this situation.

**Comment by petrukngantuk** [comment]
@jrasell yeah impacted,

I use different job per each region as workaround,

as before I define 3 region in my config n policy, all is elected to use us-east-1, the node that the job reside

**Comment by jrasell** [comment]
I am going to close this issue out. Please feel free to reach out if you experience issues or have additional questions.
