### ISSUE TITLE
Add implementation of Hetzner Cloud target plugin

### ISSUE THREAD

**Issue by AndrewChubatiuk** [hashicorp/nomad-autoscaler#465]
Hi guys
Thank you for this amazing project, already using it for services scaling
My infrastructure is in both AWS and Hetzner datacenters. I'm already using Hetzner CSI plugin for Nomad, but unfortunately there's no scaling support yet.
It would be nice to add Hetzner Cloud servers support, cause it's very cheap and unfortunately there's no out of box scaling.

**Comment by jrasell** [comment]
as discussed in the PR, this will be an external plugin.
