### ISSUE TITLE
`aws_region` not respected

### ISSUE THREAD

**Issue by nrdxp** [hashicorp/nomad-autoscaler#472]
## The Bug

Upon setting the `aws_region` config setting in the autoscaler config, we noticed that it didn't actually seem to be respected by the autoscaler. Instead it seemed to default to the region that the instance was currently deployed in. After further debugging, we also found that we could affect the region by setting `AWS_DEFAULT_REGION` in the autoscaler's environment. 

## Context

We are setting three different plugin instances, all using `aws-asg` as driver, and each with a different `aws_region` set. Only the plugin dispensed with the `aws_region` set to it's home region ended up working. The other two fail with the following:
```log
failed to describe AWS Autoscaling Group: expected 1 Autoscaling Group, got 0
```

We also did some source diving and patched in a few extra logger statements so that we could determine that the region is not being set properly. Here is some output from our custom logger to show more clearly the issue:

```log
Dispense plugin: client-us-east-2-c5-4xlarge
external_plugin.aws-asg: ASG client region: eu-central-1
```

Here you can see we are dispensing plugin intended for us-east-2 region, with it's `aws_region` being likewise set, yet logging the actual value of the region at that point in the code shows it is still using eu-cental-1 regardless of the config setting.

**Comment by jrasell** [comment]
Hi @nrdxp, thanks and apologies for reporting this bug. I believe I have identified the problem and should have a PR ready to fix this issue later this morning.

**Comment by manveru** [comment]
Thanks for the swift fix!
I tried your branch, and it indeed seems to resolve this issue. We're running this via systemd on an EC2 instance, so the metadata was probably responsible for the behavior.
