### ISSUE TITLE
bug: scaleutils can select nodes that are down / not part of target AWS ASG

### ISSUE THREAD

**Issue by alexdulin** [hashicorp/nomad-autoscaler#477]
The current implementation of [`FilterNodes`](https://github.com/hashicorp/nomad-autoscaler/blob/main/sdk/helper/scaleutils/node_identifier.go#L44) does not filter out nodes in the down state, which can lead to selecting a node for scaling in when it is both `down` but still marked [`eligible`](https://github.com/hashicorp/nomad-autoscaler/blob/main/sdk/helper/scaleutils/node_identifier.go#L82) for some reason. In this situation, if a node that is already down (say, from a prior scale-in) is selected for termination from an AWS Autoscaling group, it will result in a scaling error because the node is likely no-longer a member of the ASG due to a prior termination. Depending on the node selector strategy, this can lead to reoccurring scaling errors until the node is eventually GC'ed or other operator intervention is taken.

We have been observing this on our clusters for the past couple days. I can't explain the timing on why it just started suddenly, but there have been numerous occasions where one or more nodes have already been scaled-in and terminated by the autoscaler (thus removed from the target ASG), yet the autoscaler still selects them for scaling in on subsequent runs. Whats even more confusing is that the autoscaler is set to purge the nodes on scale-in, yet they still remain after being terminated **and left eligible.** Relevant `target` from scaling policy:

<details>
<summary>Policy target</summary>

```hcl
target "aws-asg" {
  dry-run                = "false"
  aws_asg_name           = "nomad-client-foo-XXXXXX"
  node_class             = "foo"
  node_drain_deadline    = "1h"
  node_purge             = "true"
  node_selector_strategy = "least_busy"
}
```

</details>

Two possible solutions to this problem:
1. Remove nodes that are `down` when running `FilterNodes`. This is a naive approach that assumes node's that are down are actually down and are not going to come back online (i.e. they were already terminated and are not suffering a network segmentation or similar). 
2. Verify that a given node is still a member of a target ASG or similar before attempting to terminate the node. This presumably would make sense to include in [`poolID.IsPoolMember`](https://github.com/hashicorp/nomad-autoscaler/blob/7f852a0900a1df2c886509ebc2e56d505e12d932/sdk/helper/scaleutils/cluster.go#L109) or similar. This solution would probably be more robust against scaling errors from attempting to terminate an instance in an ASG thats not actually part of it. The same logic likely applies to other cloud providers too.

### Versions of things
Nomad: 1.0.4
Nomad Autoscaler: 0.3.2

**Comment by jrasell** [comment]
Hi @alexdulin and thank you for the report. There are a several separate occurrences of odd behaviour including the node not being purged and a down node being in an eligible state. Do you have any logs available that would help better identify the potential cause of the issues you are seeing? I have a potential theory of what might be happening, however, it's something I have never seen in testing so further information to debug would be useful.

**Comment by alexdulin** [comment]
Sure thing. Here is a small subset of logs. I can share more that follow after the initial error, but its essentially the same message over and over every couple of minutes.

<details>
<summary>Log Snippet</summary>

```
{"@level":"debug","@message":"no checks need to be executed","@module":"policy_eval.worker","@timestamp":"2021-04-27T01:59:33.615279Z","id":"812f8bd0-6fee-d63d-114c-e0e705bf5b8f","policy_id":"f0567277-dc6b-6609-821b-17f3d9c958c7","queue":"horizontal","target":"nomad-target"}
{"@level":"debug","@message":"ack eval","@module":"policy_eval.broker","@timestamp":"2021-04-27T01:59:33.615298Z","eval_id":"bd6e1eb6-882b-db4a-8000-56baaed7aee4","token":"[REDACTED]"}
{"@level":"debug","@message":"eval ack'd","@module":"policy_eval.broker","@timestamp":"2021-04-27T01:59:33.615307Z","policy_id":"f0567277-dc6b-6609-821b-17f3d9c958c7"}
{"@level":"debug","@message":"dequeue eval","@module":"policy_eval.broker","@timestamp":"2021-04-27T01:59:33.615318Z","queue":"horizontal"}
{"@level":"debug","@message":"waiting for eval","@module":"policy_eval.broker","@timestamp":"2021-04-27T01:59:33.615332Z","queue":"horizontal"}
{"@level":"debug","@message":"enqueue eval","@module":"policy_eval.broker","@timestamp":"2021-04-27T01:59:57.701901Z","eval_id":"16931f55-5752-479a-702d-c78678de9855","policy_id":"c961542a-854e-93be-5e1b-286d0946733c","queue":"cluster","token":""}
{"@level":"debug","@message":"eval enqueued","@module":"policy_eval.broker","@timestamp":"2021-04-27T01:59:57.701939Z","eval_id":"16931f55-5752-479a-702d-c78678de9855","policy_id":"c961542a-854e-93be-5e1b-286d0946733c","queue":"cluster","token":""}
{"@level":"debug","@message":"eval dequeued","@module":"policy_eval.broker","@timestamp":"2021-04-27T01:59:57.701957Z","eval_id":"16931f55-5752-479a-702d-c78678de9855","policy_id":"c961542a-854e-93be-5e1b-286d0946733c","queue":"cluster","token":"[REDACTED]"}
{"@level":"debug","@message":"received policy for evaluation","@module":"policy_eval.worker","@timestamp":"2021-04-27T01:59:57.701973Z","id":"b38f62c9-cc1c-84f9-f5c6-6b8dd4dc4c4d","policy_id":"c961542a-854e-93be-5e1b-286d0946733c","queue":"cluster","target":"aws-asg"}
{"@level":"debug","@message":"fetching current count","@module":"policy_eval.worker","@timestamp":"2021-04-27T01:59:57.702022Z","id":"b38f62c9-cc1c-84f9-f5c6-6b8dd4dc4c4d","policy_id":"c961542a-854e-93be-5e1b-286d0946733c","queue":"cluster","target":"aws-asg"}
{"@level":"debug","@message":"received policy check for evaluation","@module":"policy_eval.worker.check_handler","@timestamp":"2021-04-27T01:59:58.020719Z","check":"gitlab-runner-custom-check-0","id":"b38f62c9-cc1c-84f9-f5c6-6b8dd4dc4c4d","policy_id":"c961542a-854e-93be-5e1b-286d0946733c","queue":"cluster","source":"prometheus","strategy":"target-value","target":"aws-asg"}
{"@level":"debug","@message":"querying source","@module":"policy_eval.worker.check_handler","@timestamp":"2021-04-27T01:59:58.020807Z","check":"gitlab-runner-custom-check-0","id":"b38f62c9-cc1c-84f9-f5c6-6b8dd4dc4c4d","policy_id":"c961542a-854e-93be-5e1b-286d0946733c","query":"avg(((sum(gitlab_runner_jobs{state=~\"pending|running\",node_class=\"gitlab-runner\",datacenter=\"us-east-1\"}) by (instance) / on (instance) gitlab_runner_concurrent{node_class=\"gitlab-runner\",datacenter=\"us-east-1\"})) * 100) or vector(0)","queue":"cluster","source":"prometheus","strategy":"target-value","target":"aws-asg"}
{"@level":"debug","@message":"querying Prometheus","@module":"internal_plugin.prometheus","@timestamp":"2021-04-27T01:59:58.020842Z","query":"avg(((sum(gitlab_runner_jobs{state=~\"pending|running\",node_class=\"gitlab-runner\",datacenter=\"us-east-1\"}) by (instance) / on (instance) gitlab_runner_concurrent{node_class=\"gitlab-runner\",datacenter=\"us-east-1\"})) * 100) or vector(0)","range":{"From":"2021-04-27T01:49:58.020841321Z","To":"2021-04-27T01:59:58.020841321Z"}}
{"@level":"debug","@message":"calculating new count","@module":"policy_eval.worker.check_handler","@timestamp":"2021-04-27T01:59:58.035586Z","check":"gitlab-runner-custom-check-0","count":4,"id":"b38f62c9-cc1c-84f9-f5c6-6b8dd4dc4c4d","policy_id":"c961542a-854e-93be-5e1b-286d0946733c","queue":"cluster","source":"prometheus","strategy":"target-value","target":"aws-asg"}
{"@level":"info","@message":"scaling target","@module":"policy_eval.worker","@timestamp":"2021-04-27T01:59:58.035661Z","from":4,"id":"b38f62c9-cc1c-84f9-f5c6-6b8dd4dc4c4d","meta":{"nomad_autoscaler.count.capped":true,"nomad_autoscaler.count.original":0,"nomad_autoscaler.reason_history":["scaling down because factor is 0.000000"],"nomad_policy_id":"c961542a-854e-93be-5e1b-286d0946733c"},"policy_id":"c961542a-854e-93be-5e1b-286d0946733c","queue":"cluster","reason":"capped count from 0 to 2 to stay within limits","target":"aws-asg","to":2}
{"@level":"debug","@message":"performing node selection","@module":"internal_plugin.aws-asg","@timestamp":"2021-04-27T01:59:58.117413Z","selector_strategy":"least_busy"}
{"@level":"debug","@message":"identified remote provider ID for node","@module":"internal_plugin.aws-asg","@timestamp":"2021-04-27T01:59:58.175938Z","node_id":"b123398f-bcf7-6f59-1d38-78330f288aec","remote_id":"i-0c82a546ff16162f1"}
{"@level":"debug","@message":"identified remote provider ID for node","@module":"internal_plugin.aws-asg","@timestamp":"2021-04-27T01:59:58.180325Z","node_id":"c4cbefc1-6650-8054-15d3-fa55135450c2","remote_id":"i-0095dfa6b17763a23"}
{"@level":"error","@message":"failed to evaluate policy","@module":"policy_eval.worker","@timestamp":"2021-04-27T01:59:58.180431Z","error":"failed to scale target: failed to perform scaling action: 1 selected nodes are not found within ASG","eval_id":"16931f55-5752-479a-702d-c78678de9855","eval_token":"88d30c28-d3c7-69b9-26a5-d412289cb37d","id":"b38f62c9-cc1c-84f9-f5c6-6b8dd4dc4c4d","policy_id":"c961542a-854e-93be-5e1b-286d0946733c","queue":"cluster"}
{"@level":"debug","@message":"nack eval","@module":"policy_eval.broker","@timestamp":"2021-04-27T01:59:58.180457Z","eval_id":"16931f55-5752-479a-702d-c78678de9855","token":"[REDACTED]"}
{"@level":"warn","@message":"eval delivery limit reached","@module":"policy_eval.broker","@timestamp":"2021-04-27T01:59:58.180471Z","count":1,"eval_id":"16931f55-5752-479a-702d-c78678de9855","limit":1,"policy_id":"c961542a-854e-93be-5e1b-286d0946733c","token":"[REDACTED]"}
{"@level":"debug","@message":"dequeue eval","@module":"policy_eval.broker","@timestamp":"2021-04-27T01:59:58.180495Z","queue":"cluster"}
{"@level":"debug","@message":"waiting for eval","@module":"policy_eval.broker","@timestamp":"2021-04-27T01:59:58.180533Z","queue":"cluster"}
{"@level":"debug","@message":"triggering run of handler garbage collection","@module":"internal_plugin.nomad-target","@timestamp":"2021-04-27T02:00:30.063814Z"}
{"@level":"debug","@message":"enqueue eval","@module":"policy_eval.broker","@timestamp":"2021-04-27T02:00:33.590742Z","eval_id":"366d86d2-422c-287e-0224-4b35d18ce2b3","policy_id":"f0567277-dc6b-6609-821b-17f3d9c958c7","queue":"horizontal","token":""}
{"@level":"debug","@message":"eval enqueued","@module":"policy_eval.broker","@timestamp":"2021-04-27T02:00:33.590798Z","eval_id":"366d86d2-422c-287e-0224-4b35d18ce2b3","policy_id":"f0567277-dc6b-6609-821b-17f3d9c958c7","queue":"horizontal","token":""}
{"@level":"debug","@message":"eval dequeued","@module":"policy_eval.broker","@timestamp":"2021-04-27T02:00:33.590814Z","eval_id":"366d86d2-422c-287e-0224-4b35d18ce2b3","policy_id":"f0567277-dc6b-6609-821b-17f3d9c958c7","queue":"horizontal","token":"[REDACTED]"}
{"@level":"debug","@message":"received policy for evaluation","@module":"policy_eval.worker","@timestamp":"2021-04-27T02:00:33.590831Z","id":"587814fb-7cfa-3467-a5f2-25e7269bd659","policy_id":"f0567277-dc6b-6609-821b-17f3d9c958c7","queue":"horizontal","target":"nomad-target"}
```

</details>

**Comment by jrasell** [comment]
Thanks @alexdulin. If you have any from before this time that would be ideal; I need to understand what actions where taken previous to this state occurring. Feel free to dump as much as you have and can, it's always very useful to us to understand behaviour.

**Comment by alexdulin** [comment]
Here's the entire log file from container start up until it got rotated: [nomad_autoscaler_logs.txt](https://github.com/hashicorp/nomad-autoscaler/files/6385384/nomad_autoscaler_logs.txt). The snippet I sent you was from around line 7400 I beleive.

**Comment by alexdulin** [comment]
@jrasell any update on this issue? It is continuing to occur and requires manual operator intervention to resolve, which kind of defeats the purpose of an autoacaler.

**Comment by alexdulin** [comment]
@jrasell any update on this? We are still seeing this issue and I am not sure whether hashicorp is planning on continued support of this project or not, based on the lack of maintenance. It would be helpful to have some guidance if it is indeed not planning to be maintained so we can look for solutions elsewhere.

**Comment by jrasell** [comment]
Hi @alexdulin, we are 100% planning to continue support, maintenance and feature development. Unfortunately recently, other priorities have meant we have been unable to spend time working directly on this project. We are planning on roadmapping future work soon, although I can't give a concrete timeline yet.

Once I have some updates on this roadmap i'll happily share this. Please let me know if you have any other questions.

**Comment by lgfa29** [comment]
Hi @alexdulin 👋 

Sorry for the time it took us to dig deeper into this. Looking at the logs you provided (they were great, thanks!) I was very confused as to how come this error was emitted (`1 selected nodes are not found within ASG` without [this one](https://github.com/hashicorp/nomad-autoscaler/blob/v0.3.3/plugins/builtin/target/aws-asg/plugin/aws.go#L216-L217), and to be honest, I'm still not sure how that could have happened.

But, the good news is that I think I was able to reproduce this problem, and it may also be related to https://github.com/hashicorp/nomad-autoscaler/issues/531, where the node pool filtering is being applied to clients with the same criteria but that belong to different ASGs (for example, clients with the same `node class` across multiple ASGs).

Do you think that could be your case as well? 

If this indeed your case, https://github.com/hashicorp/nomad-autoscaler/pull/535 may help you define more specific filtering by setting both `node_class` _and_ `datacenter` when selecting nodes. I'm also working on #539 which will make the node selection more reliable, as I noticed that the current implementation may cause this type of wrong filtering.

**Comment by alexdulin** [comment]
Hi @lgfa29, thanks for following up.

No, our case is not like #531. We do not have any node classes that are spread across multiple ASGs. Each `node_class` has its own distinct ASG. 

The issue we are seeing does not relate to `node_class` or `datacenter` at all, I think. Its simply that the autoscaler is selecting nodes that are marked `down` but still `eligible`. Because the autoscaler does not check that the EC2 instance the node was on is still running and not already terminated, it can incorrectly attempt to terminate an instance that is no longer associated with the ASG.  #539 does seem to be closer to addressing this problem, though.

**Comment by lgfa29** [comment]
Ah ok, thanks for the extra info. I will make sure to include a status check in #539, both for the Nomad API and the remote service API (ASG, MIG, VMSS etc.)

I will try to get it into good shape by tomorrow and provide you with a custom build for validation if you are interested.

**Comment by alexdulin** [comment]
That's great to hear! If you have a branch that could be compiled from I might be able to get it out to test this week or next. We see this problem easily every other day, so it should be clear if the issue is resolved or not after a couple days of running a potential fix.

**Comment by lgfa29** [comment]
Here is a custom build with the fix:
https://github.com/hashicorp/nomad-autoscaler/releases/tag/v0.3.4-dev%2Bd4b0a7

It was created from #539 and include a few more changes I did today to make the Autoscaler more reliable in case the cluster is not in a stable state.

Can you run this build and see if it fixes your problem?

Big thanks in advance!

**Comment by alexdulin** [comment]
Thats great, thank you. Ill give a test and let you know if I observe the issue.

**Comment by alexdulin** [comment]
Good news, it seems to no longer error out. I tested it out on an ASG where an instance was deleted, but forced the down node to be still marked eligible. With the custom build it did not error out. Switched it back to latest official release, immediately led to errors as expected.

Thanks for making this fix. Looking forward to the next official release with it!

**Comment by lgfa29** [comment]
That's great to hear! 🎉 

I will setup some testing infrastructure and leave this build running for a bit while we work on the remaining issues and PRs for the next release.

Let us know if you notice any issues.

Thank you for testing it!
