### ISSUE TITLE
policy reading nodes from outside it's asg

### ISSUE THREAD

**Issue by nrdxp** [hashicorp/nomad-autoscaler#495]
Currently we have two nomad-autoscaler policies setup for our two different aws regions, each with their own asg setup. This was working fine for a little while, but unexpectedly the autoscaler seemed to stop functioning. At first I thought it might be related to #477 and/or #479 since the error message was rather difficult to understand.

I then attempted to upgrade to 0.3.3 to see if it might improve the situation and it looks like there have been some loggin improvements that provided me with some additional information. So here is one of the errors from the log:
```log
May 28 20:46:01 core-3 6gy7fgamcxcrd59zysisagz4k5ccpj23-nomad-autsocaler[32162]: 2021-05-28T20:46:01.875Z [ERROR] external_plugin.aws-asg: selected node not found in ASG: asg_name=mantis-testnet-client-us-east-2-c5-2xlarge instance_id=i-0137d53f333d58f84 timestamp=2021-05-28T20:46:01.875Z
May 28 20:46:01 core-3 6gy7fgamcxcrd59zysisagz4k5ccpj23-nomad-autsocaler[32162]: 2021-05-28T20:46:01.875Z [ERROR] external_plugin.aws-asg: selected node not found in ASG: instance_id=i-042682300d3d4d14d asg_name=mantis-testnet-client-us-east-2-c5-2xlarge timestamp=2021-05-28T20:46:01.875Z
May 28 20:46:01 core-3 6gy7fgamcxcrd59zysisagz4k5ccpj23-nomad-autsocaler[32162]: 2021-05-28T20:46:01.875Z [ERROR] external_plugin.aws-asg: selected node not found in ASG: asg_name=mantis-testnet-client-us-east-2-c5-2xlarge instance_id=i-0d1927f6a5d99298a timestamp=2021-05-28T20:46:01.875Z
May 28 20:46:01 core-3 6gy7fgamcxcrd59zysisagz4k5ccpj23-nomad-autsocaler[32162]: 2021-05-28T20:46:01.876Z [ERROR] policy_eval.worker: failed to evaluate policy: eval_id=de16d527-9325-c08b-c5c1-ef10a4cdc1aa eval_token=48618e7b-397b-23c2-ed8d-80db74e13075 id=fbc82dae-81dd-8577-9472-a71597fab706 policy_id=97fe64d4-a892-9cd1-70e2-05d84ff96b62 queue=cluster error="failed to scale target: rpc error: code = Unknown desc = failed to perform scaling action: 3 selected nodes are not found within ASG"
```
After investigating the node ids, I was surprised to discover that the nodes did actually exist and were still properly active and registered with consul, but they were coming from our other region's asg. So for example, i-0d1927f6a5d99298a is a properly registered node, but in the eu-central-1 region in a different asg (the one our other policy is supposed to cover).

**Comment by jrasell** [comment]
Hi @nrdxp. Is it possible to share details of the policies you are using as well as the response from the [Nomad nodes API](https://www.nomadproject.io/api-docs/nodes#list-nodes) call? This would help identify the current state of the node pools and hopefully allow us to figure out a resolution;

**Comment by nrdxp** [comment]
<details><summary>policies.json</summary><p>

```json
{
  "scaling": {
    "client-eu-central-1-c5-2xlarge": {
      "enabled": true,
      "max": 6,
      "min": 1,
      "policy": {
        "check": {
          "cpu_allocated_percentage": {
            "query": "sum(nomad_client_allocated_cpu_value{datacenter=\"eu-central-1\"}*100/(nomad_client_unallocated_cpu_value{datacenter=\"eu-central-1\"}+nomad_client_allocated_cpu_value{datacenter=\"eu-central-1\"}))/count(nomad_client_allocated_cpu_value{datacenter=\"eu-central-1\"})",
            "query_window": "1m",
            "source": "victoriametrics",
            "strategy": {
              "target-value": {
                "target": 80,
                "threshold": 0.01
              }
            }
          },
          "mem_allocated_percentage": {
            "query": "sum(nomad_client_allocated_memory_value{datacenter=\"eu-central-1\"}*100/(nomad_client_unallocated_memory_value{datacenter=\"eu-central-1\"}+nomad_client_allocated_memory_value{datacenter=\"eu-central-1\"}))/count(nomad_client_allocated_memory_value{datacenter=\"eu-central-1\"})",
            "query_window": "1m",
            "source": "victoriametrics",
            "strategy": {
              "target-value": {
                "target": 80,
                "threshold": 0.01
              }
            }
          }
        },
        "cooldown": "2m",
        "evaluation_interval": "1m",
        "target": {
          "client-eu-central-1-c5-2xlarge": {
            "aws_asg_name": "mantis-testnet-client-eu-central-1-c5-2xlarge",
            "dry-run": false,
            "node_class": "client",
            "node_drain_deadline": "5m",
            "node_drain_ignore_system_jobs": false,
            "node_purge": true,
            "node_selector_strategy": "empty_ignore_system"
          }
        }
      }
    },
    "client-us-east-2-c5-2xlarge": {
      "enabled": true,
      "max": 6,
      "min": 1,
      "policy": {
        "check": {
          "cpu_allocated_percentage": {
            "query": "sum(nomad_client_allocated_cpu_value{datacenter=\"us-east-2\"}*100/(nomad_client_unallocated_cpu_value{datacenter=\"us-east-2\"}+nomad_client_allocated_cpu_value{datacenter=\"us-east-2\"}))/count(nomad_client_allocated_cpu_value{datacenter=\"us-east-2\"})",
            "query_window": "1m",
            "source": "victoriametrics",
            "strategy": {
              "target-value": {
                "target": 80,
                "threshold": 0.01
              }
            }
          },
          "mem_allocated_percentage": {
            "query": "sum(nomad_client_allocated_memory_value{datacenter=\"us-east-2\"}*100/(nomad_client_unallocated_memory_value{datacenter=\"us-east-2\"}+nomad_client_allocated_memory_value{datacenter=\"us-east-2\"}))/count(nomad_client_allocated_memory_value{datacenter=\"us-east-2\"})",
            "query_window": "1m",
            "source": "victoriametrics",
            "strategy": {
              "target-value": {
                "target": 80,
                "threshold": 0.01
              }
            }
          }
        },
        "cooldown": "2m",
        "evaluation_interval": "1m",
        "target": {
          "client-us-east-2-c5-2xlarge": {
            "aws_asg_name": "mantis-testnet-client-us-east-2-c5-2xlarge",
            "dry-run": false,
            "node_class": "client",
            "node_drain_deadline": "5m",
            "node_drain_ignore_system_jobs": false,
            "node_purge": true,
            "node_selector_strategy": "empty_ignore_system"
          }
        }
      }
    }
  }
}
```

</p>
</details>

The nodes API returns too much json to post (github won't allow me), and I'm not sure if it contains any sensitive information. What exactly would you like to see from it, so maybe I can post relevant bits?

**Comment by jrasell** [comment]
Hi @nrdxp and thanks for the initial information. I am curious if the node within each separate ASG are configured with the same [Nomad region](https://www.nomadproject.io/docs/configuration#region)? If they are and seeing that they are using the same [node_class](https://www.nomadproject.io/docs/configuration/client#node_class) identifier, then I would expect them to be grouped together, as from the view of Nomad, they are. In this case, you would need to either configure a different class per ASG, or have the instances within each ASG join as a different Nomad region. The choice depends on your architecture and constraints.

If the nodes within each ASG are each configured with different Nomad regions, then we can keep investigating.

**Comment by nrdxp** [comment]
It looks like they do both exist in the same region after all. When we initially set this up we didn't want to have separate policies per asg, but attempted to consider all resources as part of the same pool. This might be a limitation of aws_asg plugin, or maybe we just couldn't figure it out. I guess we'll have to assign different regions for now. Maybe I should relabel this to "enhance aws plugin to span multiple asgs" or something to that effect.

It is a bit strange that it worked for some weeks before any of these errors started showing, seeing as we didn't modify the configuration at all during that time.

**Comment by jrasell** [comment]
Each scaling policy has a single target, in the case of the AWS ASG plugin the target is an ASG. I don't believe we would want to change this behaviour therefore in your current setup you would need two policies, or to consolidate your nodes within a single ASG.

You mentioned that you upgraded the Nomad Autoscaler version which may account for the change in behaviour you saw. In particular in v0.3.1 we modified the AWS target plugin to use a different AWS API call to alter the ASG size. The nature of this new call meant we put extra protection around the nodes identified, to ensure they belong in the expected ASG.

I am going to go ahead and close out this issue; feel free to reach out if you have any additional questions or issues.
