### ISSUE TITLE
Support working with the `eu` site of DataDog

### ISSUE THREAD

**Issue by ezraroi** [hashicorp/nomad-autoscaler#498]
Currently the autoscaler does not support working with the none `us` site of DataDog.
According to the go api of datadog:
https://github.com/DataDog/datadog-api-client-go#changing-server

Need to enable this as part of the config of the apm

**Comment by jrasell** [comment]
Hi @ezraroi and thanks for raising this. This is certainly something that should be supported and I hopefully can work on this in the near future.

**Comment by ezraroi** [comment]
Hi @jrasell I can make a PR

**Comment by jrasell** [comment]
Hi @ezraroi, if you have the time and desire that would be great, thanks <3
