### ISSUE TITLE
Feature Request: Support for adding headers in prometheus APM

### ISSUE THREAD

**Issue by the-maldridge** [hashicorp/nomad-autoscaler#505]
In environments where a multi-tenant backend such as cortex is used any client must supply a header value as to which namespaces it wishes to query.  In strongly authenticated setups this would normally be set by some kind of proxy that validates the identity of the caller, but I believe there is plenty of value in setting it directly as well.

**Comment by jrasell** [comment]
Thanks for the report @the-maldridge. This is something we should certainly look at supporting, therefore i'll label the issue as such.

**Comment by the-maldridge** [comment]
@jrasell this is starting to become a critical item for my org.  Is there anything we can do to help incentivize this or some architecture that you can recommend that we implement and PR in?  My understanding is that this just needs to be done as an injected http.RoundTripper to the prometheus client, but how to configure that in the confines of the APM I could do with some direction on.

**Comment by lgfa29** [comment]
Closed by #522
