### ISSUE TITLE
DockerHub Images Multi-Arch Support

### ISSUE THREAD

**Issue by kholisrag** [hashicorp/nomad-autoscaler#517]
any plan to enabled docker multiarch in dockerhub,
as personally I need this nomad-autoscaler to run on arm64 server,
I can help implement it btw, where should I look at the dockerfile and command
Thanks!

**Comment by petrukngantuk** [comment]
I saw that there is already arm64 binary in nightly release, when will it be officially released?

**Comment by lgfa29** [comment]
> I saw that there is already arm64 binary in nightly release, when will it be officially released?

ARM builds are also available as official releases as well, not just nightly builds: 
https://releases.hashicorp.com/nomad-autoscaler/0.3.3/

We're working on the next release, but no specific date yet.

**Comment by kholisrag** [comment]
any update on this @lgfa29 @jrasell ??
