### ISSUE TITLE
Allow to disable the nomad source

### ISSUE THREAD

**Issue by jorgemarey** [hashicorp/nomad-autoscaler#524]
Hi, I think it would be useful to to allow disabling the nomad source.

In our case, we want to deploy two instances of nomad-autoscaler, one dealing with allocation scaling and another with node pools autoscaling. We created several policies so each of them only has whats needed (the allocation one has scale over namespaces and the node autoscaler has permissions over nodes only). Right now as they always get the policies from nomad, the one dealing with node pools (that gets the policies from the filesystem) gets and error constantly because it's trying to get them.

```
[ERROR] policy_manager: failed to call the Nomad list policies API: Unexpected response code: 403 (Permission denied)
```

I think allowing to disable the sourcing of policies from nomad would be a nice addition.

**Comment by jrasell** [comment]
Hi @jorgemarey that makes a lot of sense, thanks for raising this and a PR.
