### ISSUE TITLE
Preserve `count` on new `nomad job run` deploy

### ISSUE THREAD

**Issue by pop** [hashicorp/nomad-autoscaler#527]
When using the `nomad-autoscaler` to horizontally scale Task Groups, I noticed that every time I run `nomad job run $MY_JOB_FILE.hcl` my Task Groups are scaled **down** to my `scaling.min` value, even if it was previously at a higher auto-scaled value.

Is there some way to express "Please preserve my Task Group's current `count` when rolling out a new deployment"?

For example if my `min` is 2, but my max is `100` and my current `count` is `70`. I would like a new deployment target `70` when rolling out my change, not for my app to scale down to `2` and then back up to `70`.

<details>
<summary>My Nomad file</summary>

```hcl
job "hello-app" {
  region      = "global"
  datacenters = ["us-west-2a", "us-west-2b", "us-west-2c"]
  type        = "service"
  group "hello-app" {
    // update {
    //   scaling = "sticky"  // Looking for something like this
    // }
    network {
      port "http" {
        to = 8080
      }
    }
    service {
      name = "hello-app"
      port = "http"
      check {
        type     = "http"
        path     = "/health"
        interval = "10s"
        timeout  = "2s"
      }
      tags = [
        "traefik.enable=true",
        "traefik.http.routers.hello-app.rule=Host(`my.cluster.domain`)"
      ]
    }
    task "hello-app" {
      driver = "docker"
      config {
        image = "my.repo/hello-app:some-tag"
        ports = ["http"]
      }
      resources {
        cpu    = 250  // MHz
        memory = 128  // MiB
      }
    }
    scaling {
      enabled = true
      min = 2
      max = 11
      policy {
        cooldown = "1m"
        evaluation_interval = "1m"

        check "cpu" {
          source = "nomad"
          query = "avg_cpu"

          strategy "target-value" {
            target = 20
          }
        }
      }
    }
  }
}
```

</details>

I only recently started using `nomad-autoscaler` so this may be answered by the documentation -- if so please let me know!

I also may be misunderstanding the behavior of `nomad-autoscaler`; I only ran a few tests before coming to this conclusion.

PS: I'm loving `nomad-autoscaler`. Surprisingly easy to setup and use! ❤️

**Comment by lgfa29** [comment]
Hi @pop 👋 

Sorry for the delay in getting back you on this.

If I understood your question correctly, what you are looking for is the [`-preserve-counts`](https://www.nomadproject.io/docs/commands/job/run#preserve-counts) CLI flag, or the [`PreserveCounts`](https://www.nomadproject.io/api-docs/jobs#preservecounts) API parameter. If they are set, the `count` values in your jobspec will be ignored, and the current count value preserved.

Is this what you are looking for?

(Thank you for using Nomad and the Autoscaler! I'm glad yo hear you are enjoying it 😄)

**Comment by pop** [comment]
@lgfa29 That is exactly what I'm looking for! I don't know how I missed that in the docs. Thanks for linking those, I'll add it to my workflow 😄
