### ISSUE TITLE
Cluster autoscale fails to scale up from 0 nodes

### ISSUE THREAD

**Issue by nsmith5** [hashicorp/nomad-autoscaler#530]
**Background**
- Nomad version 1.x
- Nomad autoscaler version 2.1.0
- Target AWS ASG
- APM: Nomad

It seems its possible to scale down to zero nodes, but the autoscaler breaks at that point and can't scale back up again. Log messages like the following appear

```
2021-10-04T16:22:36.460Z [WARN]  policy_eval.worker: failed to run check: id=xxxxx policy_id=xxxxx queue=cluster target=aws-asg error="failed to query source: no nodes identified within pool"
```

**Desired outcomes**
If scale to zero isn't supported I suppose the a configuration like 

```
scaling "example" {
   min = 0
   max = x
   ....
}
```

Should probably fail fast, or the autoscaler should ignore min=0 and just scale down to 1. If scale to zero _is_ supported then something is broken I think. Perhaps its trying to query nomad APM to scale up but the query really needs to change when the node count == 0. If _any_ job is scheduled for the node_class we need to scale up, instead of trying to measure CPU and memory on nodes that don't exist

**Comment by lgfa29** [comment]
Hi @nsmith5 and @tedivm 👋 

After investigating this further I realized that there's really not good way to support scaling to zero clients with the Nomad APM....

#534 goes into more details and provide a fix to prevent the cluster from being stuck to zero. Feel free to add any comments or feedback on the approach I tool there 🙂

**Comment by tedivm** [comment]
Not being able to scale down to zero kills off a lot of important usecases. I've already dropped nomad from our plans after seeing how much hashicorp has scaled back development of it, but should you guys decide to focus on this product again I really hope you solve this problem.

**Comment by lgfa29** [comment]
> Not being able to scale down to zero kills off a lot of important usecases.

Oh sorry, I meant to mention this in my previous message but forgot about it. Scaling the cluster to zero is possible, just not using the Nomad APM plugin since once the cluster goes to zero clients there's nothing to query for usage metrics.

We have a tutorial that shows how to scale a cluster to zero and back up on-demand using Prometheus:
https://learn.hashicorp.com/tutorials/nomad/horizontal-cluster-scaling-on-demand-batch?in=nomad/autoscaler
