### ISSUE TITLE
Fix Datadog Site Documentation in 0.3.4

### ISSUE THREAD

**Issue by luckymike** [hashicorp/nomad-autoscaler#558]
0.3.4 introduces the ability to configure the Datadog endpoint (https://github.com/hashicorp/nomad-autoscaler/pull/548), unfortunately, because this defaults to an empty string, this breaks the prior behavior. This change isn't noted in the change log as breaking.

To make matters worse, the logging output when no site is configured does not flag the error (presumably b/c an empty string is a valid value, if useless), leading to inexplicable errors in the log: 

```
internal_plugin.datadog: empty time series response from datadog, try a wider query window
```

**Comment by josegonzalez** [comment]
I'd also like to point out that the valid site values - `datadoghq.com` and `datadoghq.eu` - aren't actually the sites allowed by datadog. They are [as follows](https://docs.datadoghq.com/getting_started/site/):

SITE | SITE URL | LOCATION
-- | -- | --
US1 | https://app.datadoghq.com | US
US3 | https://us3.datadoghq.com | US
US5 | https://us5.datadoghq.com | US
EU1 | https://app.datadoghq.eu | EU
US1-FED | https://app.ddog-gov.com | US

So one would expect `US1` to be a valid value based on the above table.

**Comment by luckymike** [comment]
This may actually be a bug report, b/c it looks like the above PR intended to fallback to some default behavior if `site` is set to an empty string.

There also seems to be a logging/docs error. When I configured `site = "https://app.datadoghq.com"` I got this error message:
```
2022-01-10T22:45:00.724Z [WARN]  policy_eval.worker: failed to run check: id=646193e5-8cbd-07ac-c81f-05ed4a7acf9d policy_id=9894482d-5602-de25-85df-92db24f62521 queue=cluster target=aws-asg error="failed to query source: error querying metrics from datadog: The variable site in the server URL has invalid value https://app.datadoghq.com. Must be [datadoghq.com datadoghq.eu]"```

`app.datadoghq.com` also doesn't work, even though that's what's documented in the [Agent Config example](https://www.nomadproject.io/docs/autoscaling/plugins/apm/datadog#agent-configuration-options)

**Comment by luckymike** [comment]
Using `datadoghq.com` passes validation, but it returns no metrics. It seems like the Datadog plugin is totally broken in 0.3.4.

**Comment by luckymike** [comment]
After some more debugging, we found a misconfigured policy which was causing a noop. The documentation should still be updated to clarify if site is required or not. It would be ideal to not use an empty string if no value is required, because the empty string suggests that there is no sane default. 

Also, the documentation example seems to be incorrect, as the underlying Datadog client doesn't expect the `app` subdomain: https://github.com/DataDog/datadog-api-client-go/blob/v1.0.0-beta.7/api/v2/datadog/configuration.go#L109-L127

**Comment by lgfa29** [comment]
Thanks for the follow-up @luckymike. Just to clarify, were you specifying a value for `site` or did the problem also happen even without it? The plugin doesn't set any `site` value if no config is set, so it shouldn't cause any backwards incompatibility, and use `api.datadoghq.com` since that's the Datadog client default value.

From the link you sent, the correction to our docs would this right?

```diff
apm "datadog" {
  driver = "datadog"

  config = {
    dd_api_key = "<api key>"
    dd_app_key = "<app key>"

-   site = "app.datadoghq.eu"
+   site = "datadoghq.eu"
  }
}
```

Using the example as-is I get this error message:

```
2022-01-11T19:40:01.279-0500 [WARN]  policy_eval.worker: failed to run check: id=3d7da80d-57d6-bf9a-40bf-b8ff1938f939 policy_id=ef78324e-b16b-3b41-5984-24724ac3c6ff queue=cluster target=noop-target error="failed to query source: error querying metrics from datadog: The variable site in the server URL has invalid value app.datadoghq.eu. Must be [datadoghq.com datadoghq.eu]"
```

@josegonzalez that's the link that got me confused as well, that's why I ended up adding that `app` subdomian 😕 

I can't find a page that properly documents the list of valid API sites and subdomains. The best I could find is selecting different values from the `SITE` dropdown and checking what the endpoint changes to:
![image](https://user-images.githubusercontent.com/775380/149046175-86d3d6ce-1de9-4e0a-a0b9-11ae72f99924.png)

Clicking in other values makes me think that we need to support a `subdomain` config as well 🤔 

I will update the docs to remove the `app` subdomain. Sorry for the confusion.

**Comment by luckymike** [comment]
@lgfa29 I had what I thought was a regression with the 0.3.4/0.3.4+ent binary (we were previously on an October nightly build) where we were getting no metrics back from Datadog. I stumbled on the `site` change, and thought that was the issue, but it turned out to be a misconfiguration in the queries we were sending to datadog. 

That update looks correct, it's working for us now with site configured that way (probably unnecessary, but it's clearer to set it). As far as how to specify the site correctly for the newer endpoints, the only reference I see is the code itself: https://github.com/DataDog/datadog-api-client-go/blob/v1.7.0/api/v2/datadog/configuration.go#L120-L126. It's not a great implementation from Datadog...

As a general comment about the `site` property, defaulting to an empty string doesn't feel very semantic to me. I would expect `nil` for this behavior. If the preference is to stick with the empty string, I'd clarify the behavior in the docs, as I only realized that skipped the config by looking at the actual code (and of course that led me to suspect a bug, until I found the actually issue in our config).

**Comment by lgfa29** [comment]
Ah got it thanks!

Defaulting to an empty string was bad choice of word in the docs. What I meant to say is that the Autoscaler won't set any value for `site` if one is not provided, so it will use what's set by the Datadog SDK.

But from a user perspective, that's kind of meaningless, so I [updated the docs](https://github.com/hashicorp/nomad/pull/11824/files#diff-ca0ccf3f1295ecc33dd5b6d0c692765ccd07110b5faf70007cf3a83a799ce818R33) to make the value more explicit there.

**Comment by lgfa29** [comment]
And since the doc update is merged, I'm going to close this issue for now.

But let me know if there's anything else we can add to make it better!
