### ISSUE TITLE
Horizontal Cluster Autoscaling：Whether to support Ali Cloud

### ISSUE THREAD

**Issue by chenjpu** [hashicorp/nomad-autoscaler#578]

**Comment by lgfa29** [comment]
Hi @chenjpu 👋 

For new plugins we recommend implementing it as an external [plugin](https://www.nomadproject.io/tools/autoscaling/internals/plugins) as we're not able to test and support them.

Would you be interested in working on it?

**Comment by wrli20** [comment]
> Hi @chenjpu 👋
> 
> For new plugins we recommend implementing it as an external [plugin](https://www.nomadproject.io/tools/autoscaling/internals/plugins) as we're not able to test and support them.
> 
> Would you be interested in working on it?

Ali Cloud is the biggest CSP in China. It would be very helpful if implemented. I am glad to do some contribution, just wondering if there are any open source guides for this repo?

**Comment by wrli20** [comment]
@chenjpu https://github.com/wrli20/nomad-aliyun-autoscaler hey! I am glad to introduce this repo~

**Comment by lgfa29** [comment]
Thank you for the plugin @wrli20! ❤️ 

I'm going to close this as complete now. Feel free to reach out if you need any help 🙂
