### ISSUE TITLE
Autoscaler sits idle when scaling should occur

### ISSUE THREAD

**Issue by Rumbles** [hashicorp/nomad-autoscaler#591]
This issue seems similar to #514, but that should have been fixed with #541 but we were running 0.3.6 when this happened and I believe the fix there should be included in that release...

I noticed the scaler hadn't scaled in aws instances, so I checked the logs where I see loads of messages that tell me:

```
policy_manager.policy_handler: timeout: failed to read policy in time
```

So I googled that and found #514, it seemed similar, so I tried the suggested SIGABRT, which gave me these [logs](https://gist.github.com/Rumbles/7bab91e22b7e3717387786d159a32afe).

I will look in to updating to 0.3.7 in the mean time and will update if I see further occurrences

**Comment by bluedigits** [comment]
+1 we're seeing exactly the same behaviour since a couple of months already. Only killing/restarting helps making it go away for a while ...

**Comment by Rumbles** [comment]
This looks similar to #519 as well, sorry if it's a dupe :)

**Comment by lgfa29** [comment]
Thanks for the extra info @Rumbles!

It does seem similar to #519 as in we need to improve error handling against the Nomad API. I will close this issue to center the discussion there 👍
