### ISSUE TITLE
[Telemetry] `policy_id` and `target_name` on all scaling metrics

### ISSUE THREAD

**Issue by alopezsanchez** [hashicorp/nomad-autoscaler#593]
Hi 👋🏻 

I have many policies (and targets) in my project, and when displaying the metrics in a graph, I'm finding it helpful to have those labels on `nomad-autoscaler.scale.invoke.success_count` and `nomad-autoscaler.scale.invoke.error_count`, to be able to group by those labels.

https://www.nomadproject.io/tools/autoscaling/telemetry#scaling-metrics

At the moment, I know, for example, when a scale was successful, but I would like to know which one was.

![image](https://user-images.githubusercontent.com/15221596/183322900-5290e3af-6220-4e83-8e13-ed159e53f7ce.png)

Do you think adding the labels to those metrics would make sense? Or maybe it's better to create a new one?

I could submit a new PR adding these changes, so let me know what you think! (any guidance is welcomed) :)

**Comment by attachmentgenie** [comment]
as far as i know this a global count, so adding labels wouldnt make much sense I think. The information you are looking is available in the event log. The [autoscaler learn guide](https://learn.hashicorp.com/tutorials/nomad/autoscaler-vagrant-demo?in=nomad/autoscaler#explore-the-dashboard) has an example that shows how to send that to loki and then add the scale events as annotations to graphs in grafana. hope that helps

**Comment by alopezsanchez** [comment]
@attachmentgenie, thanks for your reply! :)
I'm using the Datadog integration, and I'm not sure how I can get that data. Could you shed some light? Thanks 🙏🏻

**Comment by attachmentgenie** [comment]
and with datadog integration you mean the telemetry metrics? that is not enough, you also need to collect the logs the autoscaler outputs. have a look at the promtail example in the [demo](https://github.com/hashicorp/nomad-autoscaler-demos/blob/main/vagrant/horizontal-app-scaling/jobs/autoscaler.nomad#L90). 
Assuming you are running the autoscaler as a nomad job as well you ll have to replace the promtail part with the equivalent of the datadog agent that has host log collection configured.

**Comment by lgfa29** [comment]
Hi @alopezsanchez 👋 

That metric is currently emitted by the [worker](https://github.com/hashicorp/nomad-autoscaler/blob/v0.3.7/policyeval/base_worker.go#L333), so it does have access to extra information needed for the labels 🤔 

On a quick glance, it does sounds like it would be useful. As @attachmentgenie mentioned, we already have that in the logs. Requiring log scrapping to get this valuable information seems like a lot of overhead.

I will check with others in the team for their feedback, but in the mean time, if anyone else has any thoughts on this feel free to add them here 😄

**Comment by apersson** [comment]
+1 on this. The per-policyID success metrics would be helpful in detecting hysteresis, for example.

**Comment by lgfa29** [comment]
Circling back here, I've opened #814 to add these new labels to these metrics.
