### ISSUE TITLE
AWS ASG Instance Refresh conflicts with autoscaling

### ISSUE THREAD

**Issue by tirimia** [hashicorp/nomad-autoscaler#596]
Hello!

During an instance refresh of an AWS ASG, since the autoscaler does not know more than just the capacity of the nodes, when a client gets replaced, a scale event can trigger.

Ideally, the autoscaler would be aware that an instance refresh is ongoing and would not scale.

**Comment by lgfa29** [comment]
Thanks for the report and the PR @tirimia!

Sorry for the delay on getting it reviewed, but I intend to get back it shortly!
