### ISSUE TITLE
Add cron-like strategy

### ISSUE THREAD

**Issue by lgfa29** [hashicorp/nomad-autoscaler#61]
Some workloads with well-defined behaviour could benefit from a cron-like strategy, where task groups are scaled based on a predefined scheduled.

An example of a cron policy in a a job spec:

```hcl
scaling {
  min = 1
  max = 10

  policy {
    strategy {
      name = "cron"

      config {
        "start of business" = {
          rule     = "0 8 * * 1-5"
          count    = 10
          priority = 100
        }

        "end of business" = {
          rule     = "0 18 * * 1-5"
          count    = 3
        }

        "start of weekend" = {
          rule  = "0 0 * * 6"
          count = 1
        }
      }
    }
  }
}
```

In case of a conflict (two or more rules being satisfied) the order of precedence is set by:
1. `priority` is set
2. highest `priority` value
3. highest `count` value

**Comment by jsiebens** [comment]
@lgfa29 I've just implemented this kind of strategy as an external plugin in this repository: https://github.com/jsiebens/nomad-autoscaler-plugins.
If there is interest, I'm happy to submit a PR to add it to the builtin plugins

**Comment by lgfa29** [comment]
Hi @jsiebens, that's awesome! Thanks so much for implementing this. Are you using it yourself by any chance?

We're starting to better organize how to handle external plugins from the community. Currently we're cataloging them in  [this page](https://www.nomadproject.io/docs/autoscaling/plugins/external), so if you would like we can add yours there (or you can do it yourself by opening a PR to edit [this file](https://github.com/hashicorp/nomad/blob/main/website/content/docs/autoscaling/plugins/external/index.mdx) 😄).

Furthermore, while we were scoping and planning the work for this plugin, we found it to be a bit limiting since it only allows for a fixed `count` value. So we came up with the idea of [schedule-based autoscaling](https://github.com/hashicorp/nomad-autoscaler/issues/448) which is a bit more powerful and flexible than a plugin can be.

We would love to hear what you think about this alternative approach, as you already went through the implementation details, so feel free to add any comments in that issue 🙂 

Given that the work on this issue will be superseded by #448, I will close this one, but feel free to continue the discussion either here or in #448.
