### ISSUE TITLE
horizontal-cluster: document way to find drained but not terminated nodes

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad-autoscaler#628]
#627 will add drain metadata to nodes that the autoscaler has drained due to scale-in actions. This makes identifying these nodes via the Nomad API trivial. In the situation where the autoscaler fails between draining and terminating nodes, there is currently no reconciliation logic for new autoscaler agents to continue the process and terminate the node. To help operators in this situation, we should document a way in which operators can call the Nomad API and discover any dangling nodes caused by the described situation.

**Comment by Juanadelacuesta** [comment]
https://docs.google.com/document/d/16sP5be0HoGoJ4-zltyV5P8iTuTyMTSy14CyqpLuDUKA/edit#
