### ISSUE TITLE
aws-asg plugin: Respect scale-in protection

### ISSUE THREAD

**Issue by jaltavilla** [hashicorp/nomad-autoscaler#650]
A common operation in our infrastructure is to replace our ec2 workers. We do this by doubling the asg size and scale protecting the new workers. We then migrate work to the new workers and scale back down to the original size. However, when we tried this while horizontal scaling was enabled it terminated the new scale protected instances.

Reading the aws docs on scale protection (https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-instance-protection.html) this makes sense. The plugin uses a terminate call that is documented as not honoring the flag and we have it set to chose the instance with the least work.

I propose that the plugin should honor this flag. I think this can be accomplished by skipping instances that have `ProtectedFromScaleIn` set to true, the same way it skips unhealthy or not in service instances.

**Comment by lgfa29** [comment]
Hi @jaltavilla 👋 

That's a great suggestion and I learned something new today 😄 

I have placed this in our roadmap and it also seems like a good issue for someone looking to contribute code.

**Comment by Genas2** [comment]
Hello,

But it has to be optional and maybe even disabled by default.
We use scale in protection to prevent AWS ASG from stopping our instances to rebalance availability zones.

**Comment by lgfa29** [comment]
Thanks for the feedback @Genas2. Making it opt-in and configurable sounds like a good idea as it helps maintain backwards compatibility.

#807 implements this functionality.

**Comment by jaltavilla** [comment]
Thanks! This change is much appreciated!
