### ISSUE TITLE
Query: New release version for nomad-autoscaler

### ISSUE THREAD

**Issue by manojrkrish** [hashicorp/nomad-autoscaler#652]
Hi,

The current release version v0.3.7 for nomad-autoscaler almost an year old and seems there are significant number contributions and improvement made post that release. Are we planning to release a new version of nomad-autoscaler anytime soon?

Thanks.

**Comment by jrasell** [comment]
Hi @manojrkrish and thanks for your query. The team are working on a new HA feature which will allow the nomad-autoscaler to run multiple instances in a leader/follower pattern. Once this work has been completed, we plan to release v0.4.0. This is expected to be in the short term, although I cannot provide a precise date.

If you wanted to try out the most recent changes, we do have [nightly builds](https://github.com/hashicorp/nomad-autoscaler/releases/tag/nightly) available.

Thanks again for your question and interest <3

**Comment by manojrkrish** [comment]
Thanks @jrasell
