### ISSUE TITLE
Typo founds

### ISSUE THREAD

**Issue by javier-diaz-herrera** [hashicorp/nomad-autoscaler#653]
Hi,

I found this typos:

alloacted --> allocated

https://github.com/hashicorp/nomad-autoscaler/blob/12f053eb8b208f83c050685fbf0ac843f55bd51e/plugins/builtin/apm/nomad/plugin/job.go#L82

https://github.com/hashicorp/nomad-autoscaler/blob/12f053eb8b208f83c050685fbf0ac843f55bd51e/plugins/builtin/apm/nomad/plugin/job.go#L99

Regards.

**Comment by jrasell** [comment]
Hi @javier-diaz-herrera and thanks for raising this issue. I have opened the linked PR to fix this.
