### ISSUE TITLE
Feature: Support Nomad workload identities

### ISSUE THREAD

**Issue by tristanmorgan** [hashicorp/nomad-autoscaler#663]
This would allow the autoscaler to be run with authentication without using an external broker like Vault.

**Comment by lgfa29** [comment]
Hi @tristanmorgan 👋 

This work is being tracked in https://github.com/hashicorp/nomad-autoscaler/issues/601 so I'm going to close this one. Feel free to follow that issue for updates 🙂

**Comment by tristanmorgan** [comment]
sorry I missed the other issue.

**Comment by lgfa29** [comment]
No worries 😄
