### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by cyrilgdn** [hashicorp/nomad-autoscaler#708]
Hello,

I wanted to know if there's any plan to release a new version?

v0.3.7 is more than 1 year old and has many vulnerabilities reported.

Thanks.

**Comment by jrasell** [comment]
Hi @cyrilgdn, the team are actively working on new functionality which will result in a v0.4.0 release. I can't give an exact date when this will come out, but it will be in the near term. Until that time, we do also produce [nightly builds](https://github.com/hashicorp/nomad-autoscaler/releases/tag/nightly) that can be used for testing and dev envs.

**Comment by cyrilgdn** [comment]
@jrasell Thanks, great news! Looking forward this new release.

It would have been nice to have security patches on existing version though.
`nomad-autoscaler` has made it to the top of our security team's vulnerabilities dashboard, for the production environment it can be problematic as we cannot use the nightly build.
