### ISSUE TITLE
release: v0.4.0 release

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad-autoscaler#753]
Once Nomad v1.7.0 has gone GA, the Nomad Autoscaler dependency should be updated, and v0.4.0 released. This process should include beta and RC builds, to allow testing before GA due to significant recent changes.

**Comment by lgfa29** [comment]
[v0.4.0](https://releases.hashicorp.com/nomad-autoscaler/0.4.0/) has been released 🎉
