### ISSUE TITLE
Fail to start in high availability mode when using `namespace = "*"`

### ISSUE THREAD

**Issue by livioribeiro** [hashicorp/nomad-autoscaler#828]
When running in high availability mode, the namespace used to acquire the lock is the same declared in the `nomad` stanza in the autoscaler configuration, so using `namespace = "*"` with high availability enabled causes an error when acquiring the lock with the api returning status 403.

One possible solution would be to use for the lock the same namespace where the job is running instead of the one defined in the `nomad` stanza. I do not know a lot of Go but I believe that it can be defined in the `api.WriteOptions{}` in this line:
 
https://github.com/hashicorp/nomad-autoscaler/blob/cbd0ccb444dc4f226357b4466bccc90183be4262/command/agent.go#L411

**Comment by lgfa29** [comment]
Thank you for the report @livioribeiro!

You're absolutely right, we need to specify a single namespace for the variable. But using the autoscaler job namespace is not quite reliable, as it may not be running in Nomad (we even have people running it on Kubernetes 😄).

I opened #832 to add a new config for this. You use the [`NOMAD_NAMESAPCE` env var](https://developer.hashicorp.com/nomad/docs/runtime/environment#job-related-variables) in your job to get the behaviour your described.
