### ISSUE TITLE
Datadog APM: Including `now` in time range causes incorrect scaling actions

### ISSUE THREAD

**Issue by jaltavilla** [hashicorp/nomad-autoscaler#843]
We setup scaling policies using the datadog apm with both the aws-asg plugin for ec2 instances and the nomad-target for jobs. In both cases we used the target strategy to scale (policies below). When we did this, we discovered that scaling actions would occur seemingly randomly. The service or asg could be underutilized and still double or triple in scale then scale down to the expected amount after the policy cooldown expired.

After some investigation we discovered that the cause of this was that the datadog query was sometimes returning incorrect values for the most recent point(s), combined with the target strategy only using the last point in the series. This could also be seen on the dashboards; the point for the current minute would sometimes spike up or down for a few seconds before correcting itself. I spent some time working with datadog support to try and resolve this. Ultimately they said that including `now` in the query would always potentially lead to these results. Which makes sense to me; data is still coming in from the agents for the current time.

> I have reviewed this issue further with the Engineering team, and unfortunately the spike occurring seems to be a product of the live  timeframe query. This means that as long as the timeframe is querying a constant time, like past X minutes, the spike will keep  happening. 
 >
>The suggested workaround is to use a timeframe that doesn't have the live aspect and avoids the most recent minute. For example - if I'm querying at 01:00pm, to get complete data I'd query from 12:44pm-12:59pm (i.e. give 1min for the data to show up). It would take extra work on the front end to write a script that changes time intervals, but would ultimately end in similar data as a live timeframe. 

I searched the issues and hashicorp forums and was a bit surprised that no one else had experienced this. I modified policyeval/base_worker.go's generation of the range `to := time.Now().Add(-1 * time.Minute)` to test datadog's suggestion. So far this seems to have fixed it for us. (Although this would affect all apms)

It would be nice if the datadog apm either shifted the query window, or maybe better allowed it via config. The use case config would be nice for is to scale based on the prior weeks behavior. Our services tend to experience similar load on a weekly cadence. Datadog has a `week_before` function that can be used in a check. However, querying the week before at now isn't helpful because we are already experiencing the same load. But, if we used week_before with a timeshift of +15 minutes we could scale just ahead of time, 

Thanks!

aws-asg policy snippet
```
        check "cpu-allocated" {
            source          = "datadog"
            query           = "(100*sum:nomad.client.allocated.cpu{env:ronin-prod,autoscaling_group:mgp-worker-2a}.rollup(sum)) / (env:ronin-prod,autoscaling_group:mgp-worker-2a}.rollup(sum) + sum:nomad.client.unallocated.cpu{env:ronin-prod,autoscaling_group:mgp-worker-2a}.rollup(sum))"
            query_window    = "3m"
            strategy "target-value" {
                target = 85
            }
        }
```

job policy snippet
```			
"source": "datadog",
"query": fmt.Sprintf(
    "clamp_max("+
	"100*ewma_20(sum:nomad.client.allocs.cpu.total_ticks{env:%[1]s,job:%[2]s}.fill(last))"+
	" / sum:nomad.client.allocs.cpu.allocated{env:%[1]s,job:%[2]s}.fill(last)"+
	", 200)", cluster.Environment, svc.Name),
"query_window": "15m",
"strategy": []interface{}{
map[string]interface{}{
	"target-value": []interface{}{
		map[string]interface{}{
			"target": 85,
		},
	},
},
```

**Comment by lgfa29** [comment]
Hi @jaltavilla 👋 

I really like this idea! I kind of suspected that using `time.Now()` could cause issues (Prometheus also has some unexpected results at the very tip), but I was never able to prove. Thank you for reaching out to Datadog and getting official confirmation.

But I specially like how you describe the predictive scaling based on historical metrics. From the implementation in #850 I think you can achieve this like so:

```hcl
check "active_connections" {
  source              = "..."
  query               = "..."
  query_window        = "5m"
  query_window_offset = "168h15m" # 7 * 24h + 15m
  # ...
}
```

Very clever idea! Thank you for the suggestion 🙂

**Comment by jaltavilla** [comment]
Thanks for working on this so quickly!

You are right that we don't need the week_before function, and can instead use a longer offset duration to look at any historical time. I think for predictive scaling, we would probably start with `query_window_offset = 167h45m   # 7 * 24h - 15m`.  Since say at 03:00, we want to scale up to what the load was at 03:15 a week ago. Which is slightly less than a full week ago. (15 minutes being some arbitrary time to allow cooldown periods to end and ec2 instances to start up if needed)

**Comment by lgfa29** [comment]
Ops, that's right. I moved the window 15min in the wrong direction 😅
