### ISSUE TITLE
Different cooldowns for scaling up and down?

### ISSUE THREAD

**Issue by brmzkw** [hashicorp/nomad-autoscaler#858]
When a scaling action is triggered and the count of a task group is changed, the autoscaling policy is put into cooldown. The cooldown applies for both scale up and scale down operations.

What do you think about adding two new parameters, `up_cooldown` and `down_cooldown`? (better names suggestions welcome!)

With a short `up_cooldown`(5s) and a higher `down_cooldown` (10m), we could ensure an application scales up almost immediately but takes time to scale down.

**Comment by lgfa29** [comment]
Hi @brmzkw 👋 

Thank you for the suggestion! We actually already have an issue to track this request (https://github.com/hashicorp/nomad-autoscaler/issues/272) so I'm going to close this one to focus the discussion in a single place.

Feel free to add more thoughts and comments there. 

Thanks again!
