### ISSUE TITLE
publish nightly docker images

### ISSUE THREAD

**Issue by cgbaker** [hashicorp/nomad-autoscaler#88]
docker images with an appropriate tag (`nightly`,`nightly-{date}`, `latest-nightly`, ...) should be published as part of the nightly build.

**Comment by josegonzalez** [comment]
Is this something you would take a pull request for?

**Comment by jrasell** [comment]
Hi @josegonzalez, unfortunately the Nomad Autoscaler release pipelines reside in a private GitHub repository so community contributions are not possible.
